// Code generated by cmd/generate-enums; DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
)

// --- Direction ---

// String returns the canonical string representation.
func (d Direction) String() string {
	switch d {
	case Auto:
		return "AUTO"
	case Down:
		return "DOWN"
	case Up:
		return "UP"
	case Right:
		return "RIGHT"
	case Left:
		return "LEFT"
	default:
		return "unknown"
	}
}

// ParseDirection converts a string to a Direction.
func ParseDirection(s string) (Direction, error) {
	switch s {
	case "AUTO", "UNDEFINED", "":
		return Auto, nil
	case "DOWN":
		return Down, nil
	case "UP":
		return Up, nil
	case "RIGHT":
		return Right, nil
	case "LEFT":
		return Left, nil
	default:
		return Auto, fmt.Errorf("unknown direction: %q", s)
	}
}

// MarshalJSON encodes Direction as its canonical string representation.
func (d Direction) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.String())
}

// UnmarshalJSON decodes Direction from its string representation.
func (d *Direction) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("direction: %w", err)
	}
	v, err := ParseDirection(str)
	if err != nil {
		return fmt.Errorf("direction: %w", err)
	}
	*d = v
	return nil
}

// --- Shape ---

// String returns the canonical string representation.
func (s Shape) String() string {
	switch s {
	case ShapeRect:
		return "rect"
	case ShapeRounded:
		return "rounded"
	case ShapeCircle:
		return "circle"
	case ShapeDiamond:
		return "diamond"
	case ShapeCylinder:
		return "cylinder"
	case ShapeHexagon:
		return "hexagon"
	case ShapeParallelogram:
		return "parallelogram"
	default:
		return "unknown"
	}
}

// ParseShape converts a string to a Shape.
func ParseShape(s string) (Shape, error) {
	switch s {
	case "rect", "":
		return ShapeRect, nil
	case "rounded":
		return ShapeRounded, nil
	case "circle":
		return ShapeCircle, nil
	case "diamond":
		return ShapeDiamond, nil
	case "cylinder":
		return ShapeCylinder, nil
	case "hexagon":
		return ShapeHexagon, nil
	case "parallelogram":
		return ShapeParallelogram, nil
	default:
		return ShapeRect, fmt.Errorf("unknown shape: %q", s)
	}
}

// MarshalJSON encodes Shape as its canonical string representation.
func (s Shape) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// UnmarshalJSON decodes Shape from its string representation.
func (s *Shape) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("shape: %w", err)
	}
	v, err := ParseShape(str)
	if err != nil {
		return fmt.Errorf("shape: %w", err)
	}
	*s = v
	return nil
}

// --- EdgeStyle ---

// String returns the canonical string representation.
func (e EdgeStyle) String() string {
	switch e {
	case EdgeSolid:
		return "solid"
	case EdgeDashed:
		return "dashed"
	case EdgeDotted:
		return "dotted"
	case EdgeThick:
		return "thick"
	default:
		return "unknown"
	}
}

// ParseEdgeStyle converts a string to a EdgeStyle.
func ParseEdgeStyle(s string) (EdgeStyle, error) {
	switch s {
	case "solid", "":
		return EdgeSolid, nil
	case "dashed":
		return EdgeDashed, nil
	case "dotted":
		return EdgeDotted, nil
	case "thick":
		return EdgeThick, nil
	default:
		return EdgeSolid, fmt.Errorf("unknown edge style: %q", s)
	}
}

// MarshalJSON encodes EdgeStyle as its canonical string representation.
func (e EdgeStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.String())
}

// UnmarshalJSON decodes EdgeStyle from its string representation.
func (e *EdgeStyle) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("edge style: %w", err)
	}
	v, err := ParseEdgeStyle(str)
	if err != nil {
		return fmt.Errorf("edge style: %w", err)
	}
	*e = v
	return nil
}

// --- EdgeDirection ---

// String returns the canonical string representation.
func (d EdgeDirection) String() string {
	switch d {
	case EdgeForward:
		return "forward"
	case EdgeBackward:
		return "backward"
	case EdgeBoth:
		return "both"
	case EdgeNone:
		return "none"
	default:
		return "unknown"
	}
}

// ParseEdgeDirection converts a string to a EdgeDirection.
func ParseEdgeDirection(s string) (EdgeDirection, error) {
	switch s {
	case "forward", "":
		return EdgeForward, nil
	case "backward":
		return EdgeBackward, nil
	case "both":
		return EdgeBoth, nil
	case "none":
		return EdgeNone, nil
	default:
		return EdgeForward, fmt.Errorf("unknown edge direction: %q", s)
	}
}

// MarshalJSON encodes EdgeDirection as its canonical string representation.
func (d EdgeDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.String())
}

// UnmarshalJSON decodes EdgeDirection from its string representation.
func (d *EdgeDirection) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("edge direction: %w", err)
	}
	v, err := ParseEdgeDirection(str)
	if err != nil {
		return fmt.Errorf("edge direction: %w", err)
	}
	*d = v
	return nil
}

// --- InteractionStyle ---

// String returns the canonical string representation.
func (s InteractionStyle) String() string {
	switch s {
	case InteractionSolid:
		return "solid"
	case InteractionDashed:
		return "dashed"
	case InteractionAsync:
		return "async"
	default:
		return "unknown"
	}
}

// ParseInteractionStyle converts a string to a InteractionStyle.
func ParseInteractionStyle(s string) (InteractionStyle, error) {
	switch s {
	case "solid", "":
		return InteractionSolid, nil
	case "dashed":
		return InteractionDashed, nil
	case "async":
		return InteractionAsync, nil
	default:
		return InteractionSolid, fmt.Errorf("unknown interaction style: %q", s)
	}
}

// MarshalJSON encodes InteractionStyle as its canonical string representation.
func (s InteractionStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// UnmarshalJSON decodes InteractionStyle from its string representation.
func (s *InteractionStyle) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("interaction style: %w", err)
	}
	v, err := ParseInteractionStyle(str)
	if err != nil {
		return fmt.Errorf("interaction style: %w", err)
	}
	*s = v
	return nil
}

// --- FragmentType ---

// String returns the canonical string representation.
func (f FragmentType) String() string {
	switch f {
	case FragmentAlt:
		return "alt"
	case FragmentOpt:
		return "opt"
	case FragmentLoop:
		return "loop"
	case FragmentPar:
		return "par"
	case FragmentBreak:
		return "break"
	default:
		return "unknown"
	}
}

// ParseFragmentType converts a string to a FragmentType.
func ParseFragmentType(s string) (FragmentType, error) {
	switch s {
	case "alt":
		return FragmentAlt, nil
	case "opt":
		return FragmentOpt, nil
	case "loop":
		return FragmentLoop, nil
	case "par":
		return FragmentPar, nil
	case "break":
		return FragmentBreak, nil
	default:
		return FragmentAlt, fmt.Errorf("unknown fragment type: %q", s)
	}
}

// MarshalJSON encodes FragmentType as its canonical string representation.
func (f FragmentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(f.String())
}

// UnmarshalJSON decodes FragmentType from its string representation.
func (f *FragmentType) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("fragment type: %w", err)
	}
	v, err := ParseFragmentType(str)
	if err != nil {
		return fmt.Errorf("fragment type: %w", err)
	}
	*f = v
	return nil
}

// --- Relation ---

// String returns the canonical string representation.
func (r Relation) String() string {
	switch r {
	case RelationNone:
		return ""
	case RelationAssociation:
		return "association"
	case RelationInheritance:
		return "inheritance"
	case RelationRealization:
		return "realization"
	case RelationDependency:
		return "dependency"
	case RelationAggregation:
		return "aggregation"
	case RelationComposition:
		return "composition"
	default:
		return "unknown"
	}
}

// ParseRelation converts a string to a Relation.
func ParseRelation(s string) (Relation, error) {
	switch s {
	case "":
		return RelationNone, nil
	case "association":
		return RelationAssociation, nil
	case "inheritance":
		return RelationInheritance, nil
	case "realization":
		return RelationRealization, nil
	case "dependency":
		return RelationDependency, nil
	case "aggregation":
		return RelationAggregation, nil
	case "composition":
		return RelationComposition, nil
	default:
		return RelationNone, fmt.Errorf("unknown relation: %q", s)
	}
}

// MarshalJSON encodes Relation as its canonical string representation.
func (r Relation) MarshalJSON() ([]byte, error) {
	return json.Marshal(r.String())
}

// UnmarshalJSON decodes Relation from its string representation.
func (r *Relation) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("relation: %w", err)
	}
	v, err := ParseRelation(str)
	if err != nil {
		return fmt.Errorf("relation: %w", err)
	}
	*r = v
	return nil
}
