// Command generate-enums produces String, Parse, MarshalJSON, and UnmarshalJSON
// methods for enum types in the model package.
//
// Usage: go run ./cmd/generate-enums
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

type enumValue struct {
	Name    string   // Go constant name, e.g. "Down"
	Strings []string // accepted string representations; first is canonical
	Default bool     // returned when Parse receives ""
}

type enumDef struct {
	TypeName   string      // Go type name, e.g. "Direction"
	Receiver   string      // single-char receiver, e.g. "d"
	ErrorLabel string      // label in error messages, e.g. "direction"
	BaseType   string      // "int" or "string" — string enums skip Parse/JSON
	Values     []enumValue // ordered list of values
}

var enums = []enumDef{
	{
		TypeName: "Direction", Receiver: "d", ErrorLabel: "direction", BaseType: "int",
		Values: []enumValue{
			{Name: "Auto", Strings: []string{"AUTO", "UNDEFINED"}, Default: true},
			{Name: "Down", Strings: []string{"DOWN"}},
			{Name: "Up", Strings: []string{"UP"}},
			{Name: "Right", Strings: []string{"RIGHT"}},
			{Name: "Left", Strings: []string{"LEFT"}},
		},
	},
	{
		TypeName: "Shape", Receiver: "s", ErrorLabel: "shape", BaseType: "int",
		Values: []enumValue{
			{Name: "ShapeRect", Strings: []string{"rect"}, Default: true},
			{Name: "ShapeRounded", Strings: []string{"rounded"}},
			{Name: "ShapeCircle", Strings: []string{"circle"}},
			{Name: "ShapeDiamond", Strings: []string{"diamond"}},
			{Name: "ShapeCylinder", Strings: []string{"cylinder"}},
			{Name: "ShapeHexagon", Strings: []string{"hexagon"}},
			{Name: "ShapeParallelogram", Strings: []string{"parallelogram"}},
		},
	},
	{
		TypeName: "EdgeStyle", Receiver: "e", ErrorLabel: "edge style", BaseType: "int",
		Values: []enumValue{
			{Name: "EdgeSolid", Strings: []string{"solid"}, Default: true},
			{Name: "EdgeDashed", Strings: []string{"dashed"}},
			{Name: "EdgeDotted", Strings: []string{"dotted"}},
			{Name: "EdgeThick", Strings: []string{"thick"}},
		},
	},
	{
		TypeName: "EdgeDirection", Receiver: "d", ErrorLabel: "edge direction", BaseType: "int",
		Values: []enumValue{
			{Name: "EdgeForward", Strings: []string{"forward"}, Default: true},
			{Name: "EdgeBackward", Strings: []string{"backward"}},
			{Name: "EdgeBoth", Strings: []string{"both"}},
			{Name: "EdgeNone", Strings: []string{"none"}},
		},
	},
	{
		TypeName: "InteractionStyle", Receiver: "s", ErrorLabel: "interaction style", BaseType: "int",
		Values: []enumValue{
			{Name: "InteractionSolid", Strings: []string{"solid"}, Default: true},
			{Name: "InteractionDashed", Strings: []string{"dashed"}},
			{Name: "InteractionAsync", Strings: []string{"async"}},
		},
	},
	{
		TypeName: "FragmentType", Receiver: "f", ErrorLabel: "fragment type", BaseType: "int",
		Values: []enumValue{
			{Name: "FragmentAlt", Strings: []string{"alt"}},
			{Name: "FragmentOpt", Strings: []string{"opt"}},
			{Name: "FragmentLoop", Strings: []string{"loop"}},
			{Name: "FragmentPar", Strings: []string{"par"}},
			{Name: "FragmentBreak", Strings: []string{"break"}},
		},
	},
	{
		TypeName: "Relation", Receiver: "r", ErrorLabel: "relation", BaseType: "int",
		Values: []enumValue{
			// RelationNone is the zero value: a flow edge. Its canonical
			// string is "" so ParseRelation("") is RelationNone and the
			// JSON omitempty tag drops it; it is deliberately NOT Default
			// (a Default entry would emit a duplicate `case ""`).
			{Name: "RelationNone", Strings: []string{""}},
			{Name: "RelationAssociation", Strings: []string{"association"}},
			{Name: "RelationInheritance", Strings: []string{"inheritance"}},
			{Name: "RelationRealization", Strings: []string{"realization"}},
			{Name: "RelationDependency", Strings: []string{"dependency"}},
			{Name: "RelationAggregation", Strings: []string{"aggregation"}},
			{Name: "RelationComposition", Strings: []string{"composition"}},
		},
	},
}

var enumTmpl = template.Must(template.New("enum").Funcs(template.FuncMap{
	"join": strings.Join,
}).Parse(`// Code generated by cmd/generate-enums; DO NOT EDIT.

package model

import (
	"encoding/json"
	"fmt"
)
{{ range . }}
// --- {{ .TypeName }} ---

// String returns the canonical string representation.
func ({{ .Receiver }} {{ .TypeName }}) String() string {
	switch {{ .Receiver }} {
	{{- range .Values }}
	case {{ .Name }}:
		return "{{ index .Strings 0 }}"
	{{- end }}
	default:
		return "unknown"
	}
}

// Parse{{ .TypeName }} converts a string to a {{ .TypeName }}.
func Parse{{ .TypeName }}(s string) ({{ .TypeName }}, error) {
	switch s {
	{{- range .Values }}
	case {{ range $i, $str := .Strings }}{{ if $i }}, {{ end }}"{{ $str }}"{{ end }}{{ if .Default }}, ""{{ end }}:
		return {{ .Name }}, nil
	{{- end }}
	default:
		return {{ (index .Values 0).Name }}, fmt.Errorf("unknown {{ .ErrorLabel }}: %q", s)
	}
}
{{ if eq .BaseType "int" }}
// MarshalJSON encodes {{ .TypeName }} as its canonical string representation.
func ({{ .Receiver }} {{ .TypeName }}) MarshalJSON() ([]byte, error) {
	return json.Marshal({{ .Receiver }}.String())
}

// UnmarshalJSON decodes {{ .TypeName }} from its string representation.
func ({{ .Receiver }} *{{ .TypeName }}) UnmarshalJSON(data []byte) error {
	var str string
	if err := json.Unmarshal(data, &str); err != nil {
		return fmt.Errorf("{{ .ErrorLabel }}: %w", err)
	}
	v, err := Parse{{ .TypeName }}(str)
	if err != nil {
		return fmt.Errorf("{{ .ErrorLabel }}: %w", err)
	}
	*{{ .Receiver }} = v
	return nil
}
{{ end }}{{ end }}
`))

func main() {
	outPath := "enums_gen.go"

	var buf bytes.Buffer
	if err := enumTmpl.Execute(&buf, enums); err != nil {
		fmt.Fprintf(os.Stderr, "template: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt: %v\n", err)
		os.WriteFile(outPath, buf.Bytes(), 0o644) //nolint:errcheck
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("generated %s\n", outPath)
}
